# Default values for odmcharts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ""
  pullPolicy: IfNotPresent
## Optionally specify an array of imagePullSecrets.
## Secrets must be manually created in the namespace.
## ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
##  - name: admin.registrykey
  pullSecrets:

## Architecture - e.g. amd64, ppc64le. If left empty, the architecture will be determined automatically.
## You can use kubectl version command to determine the architecture on the desired worker node.
  arch: ""

service:
  enableTLS: true
  type: NodePort

decisionServerRuntime:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 4096Mi

decisionServerConsole:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 1024Mi

decisionCenter:
  enabled: true
  persistenceLocale: en_US
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 4096Mi

decisionRunner:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 4096Mi

internalDatabase:
  databaseName: odmdb
  user: odmusr
  password: "odmpwd"
  persistence:
    enabled: true
    useDynamicProvisioning: false
    storageClassName: ""
    resources:
      requests:
        storage: 5Gi
  securityContext:
    runAsUser: 0
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 4096Mi

externalDatabase:
  type: ""
  serverName: ""
  databaseName: ""
  user: ""
  password: ""
  port: ""

externalCustomDatabase:
  datasourceRef:
  driverPvc:

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 45
  timeoutSeconds: 5

livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 10
  failureThreshold: 10
  timeoutSeconds: 5

customization:
  securitySecretRef:
  baiEmitterSecretRef:
  authSecretRef:
  dedicatedNodeLabel:

  productName: IBM Cloud Pak for Automation
  productID: 5737-I23
  kubeVersion: DBAMC
