kind: Deployment
apiVersion: apps/v1
metadata:
  name: zen-backup
  namespace: <zenservice namespace>
  labels:
    foundationservices.cloudpak.ibm.com: zen-data
spec:
  selector:
    matchLabels:
      foundationservices.cloudpak.ibm.com: zen-data
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: zendump
        pre.hook.backup.velero.io/command: '["sh", "-c", "/zen4/zen4-br.sh <zenservice namespace> true"]'
        pre.hook.backup.velero.io/timeout: 300s
        post.hook.restore.velero.io/command: '["sh", "-c", "/zen4/zen4-br.sh <zenservice namespace> false"]'
        post.hook.restore.velero.io/wait-timeout: 300s
        post.hook.restore.velero.io/exec-timeout: 300s
        post.hook.restore.velero.io/timeout: 600s
      name: zen-backup
      namespace: <zenservice namespace>
      labels:
        foundationservices.cloudpak.ibm.com: zen-data
    spec:
        containers:
        - command:
          - sh
          - -c
          - sleep infinity
          image: icr.io/cpopen/cpfs/cpfs-utils:4.3.0
          imagePullPolicy: IfNotPresent
          name: zen4-backup-restore
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 512Mi
              memory: 512Mi
            requests:
              cpu: 200m
              ephemeral-storage: 128Mi
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /user-home
            name: user-home-mount
          - mountPath: /certs
            name: metastore-secret
          - mountPath: /tmp/backup
            name: zen-metastoredb-backup-scripts
          - name: scripts
            mountPath: "/zen4"
          - name: ext
            mountPath: /zen4/extensions
        dnsPolicy: ClusterFirst
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        serviceAccount: zen4-backup-sa
        serviceAccountName: zen4-backup-sa
        terminationGracePeriodSeconds: 30
        volumes:
        - name: user-home-mount
          persistentVolumeClaim:
            claimName: zen-backup-pvc
        - name: metastore-secret
          secret:
            defaultMode: 484
            secretName: metastore-secret
        - configMap:
            defaultMode: 511
            name: zen-metastoredb-backup-scripts
          name: zen-metastoredb-backup-scripts
        - name: scripts
          configMap:
            name: zen4-br-configmap
            defaultMode: 0777
        - emptyDir: {}
          name: ext