kind: Deployment
apiVersion: apps/v1
metadata:
  name: cs-db-backup
  namespace: <cs-db namespace>
spec:
  selector:
    matchLabels:
      foundationservices.cloudpak.ibm.com: cs-db-data
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: cs-db-backup
        pre.hook.backup.velero.io/command: '["sh", "-c", "/cs-db/br_cs-db.sh backup <cs-db namespace>"]'
        pre.hook.backup.velero.io/timeout: 300s
        post.hook.backup.velero.io/command: '["sh", "-c", "rm -rf /cs-db/cs-db-backup/database"]'
        post.hook.restore.velero.io/command: '["sh", "-c", "/cs-db/br_cs-db.sh restore <cs-db namespace>"]'
        post.hook.restore.velero.io/wait-timeout: 300s
        post.hook.restore.velero.io/exec-timeout: 300s
        post.hook.restore.velero.io/timeout: 720s
      name: cs-db-backup
      namespace: <cs-db namespace>
      labels:
        foundationservices.cloudpak.ibm.com: cs-db-data
    spec:
        containers:
        - command:
          - sh
          - -c
          - sleep infinity
          image: icr.io/cpopen/cpfs/cpfs-utils:4.3.0 #4.1.0 if using CS 4.1, 4.2.0 if using CS 4.2
          imagePullPolicy: IfNotPresent
          name: cs-db-br
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 512Mi
              memory: 512Mi
            requests:
              cpu: 200m
              ephemeral-storage: 128Mi
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /cs-db/cs-db-backup
            name: cs-db-backup-mount
          - name: scripts
            mountPath: "/cs-db"
        dnsPolicy: ClusterFirst
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        serviceAccount: cs-db-backup-sa
        serviceAccountName: cs-db-backup-sa
        terminationGracePeriodSeconds: 30
        volumes:
        - name: cs-db-backup-mount
          persistentVolumeClaim:
            claimName: cs-db-backup-pvc
        - name: scripts
          configMap:
            name: cs-db-br-configmap
            defaultMode: 0777