###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: application
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 21.0.2
spec:
  appVersion: 21.0.2

  ## MUST exist, used to accept ibm license, valid value only can be "accept" 
  ibm_license: ""

  ## TIPS: The names of all variables in the spec field are converted to snake_case by the operator before running ansible
  ## For example, serviceAccount in the spec becomes service_account in ansible.
  ## It is recommended that you perform some type validation in Ansible on the variables to ensure that
  ## your application is receiving expected input.
  ## shared configuration among all tribe
  shared_configuration:
    sc_deployment_patterns: application
    sc_optional_components: app_designer
    sc_deployment_type: demo
    sc_deployment_platform: OCP

  ## This is the deployment hostname suffix, this is optional and the default hostname suffix will be used as {meta.namespace}.router-canonicalhostname
    # sc_deployment_hostname_suffix:
    root_ca_secret: "{{ meta.name }}-root-ca"
    image_pull_secrets:
    - image-pull-secret
    storage_configuration:
      sc_dynamic_storage_classname: ""
  ########################################################################
  ########   IBM Business Automation Navigator configuration      ########
  ########################################################################
  navigator_configuration:
    image:
      repository: cp.icr.io/cp/cp4a/ban/navigator-sso
      tag: ga-3010-icn
  ########################################################################
  ########      IBM Business Automation Studio configuration      ########
  ########################################################################
  bastudio_configuration:
    images:
      bastudio:
        repository: cp.icr.io/cp/cp4a/bas/bastudio
        tag: 21.0.2-IF001
    jms_server:
      image:
        repository: cp.icr.io/cp/cp4a/bas/jms
        tag: 21.0.2-IF001
    playback_server:
      images:
        db_job:
          repository: cp.icr.io/cp/cp4a/bas/solution-server-helmjob-db
          tag: 21.0.2-IF001
        solution_server:
          repository: cp.icr.io/cp/cp4a/bas/solution-server
          tag: 21.0.2-IF001
  ########################################################################
  ########      IBM Resource Registry configuration               ########
  ########################################################################
  resource_registry_configuration:
    images:
      resource_registry:
        repository: cp.icr.io/cp/cp4a/aae/dba-etcd
        tag: 21.0.2-IF001
        
  ########################################################################
  ########   IBM User and Group Management Service configuration  ########
  ########################################################################
  ums_configuration:
    teamserver:
      admingroup: 'cn=ADPEnvironmentOwners,dc=example,dc=org'
      