###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2020. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: application
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 20.0.2.1
spec:
  appVersion: 20.0.2.1
  ## TIPS: The names of all variables in the spec field are converted to snake_case by the operator before running ansible
  ## For example, serviceAccount in the spec becomes service_account in ansible.
  ## It is recommended that you perform some type validation in Ansible on the variables to ensure that
  ## your application is receiving expected input.
  ## shared configuration among all tribe
  shared_configuration:
    sc_deployment_patterns: application
    sc_optional_components: app_designer
    sc_deployment_type: demo
    sc_deployment_platform: OCP
    sc_deployment_hostname_suffix: "{{ meta.name }}"
    root_ca_secret: "{{ meta.name }}-root-ca"
    image_pull_secrets:
    - image-pull-secret
    storage_configuration:
      sc_dynamic_storage_classname: ""
    images:
      keytool_job_container:
        repository: cp.icr.io/cp/cp4a/ums/dba-keytool-jobcontainer
        tag: 20.0.2-IF002
      dbcompatibility_init_container:
        repository: cp.icr.io/cp/cp4a/aae/dba-dbcompatibility-initcontainer
        tag: 20.0.2-IF002
      keytool_init_container:
        repository: cp.icr.io/cp/cp4a/ums/dba-keytool-initcontainer
        tag: 20.0.2-IF002
      umsregistration_initjob:
        repository: cp.icr.io/cp/cp4a/aae/dba-umsregistration-initjob
        tag: 20.0.2-IF002
      db2u_tools:
        repository: docker.io/ibmcom/db2u.tools
        tag: 11.5.1.0-CN1
      db2:
        repository: docker.io/ibmcom/db2
        tag: 11.5.1.0-CN1
      db2_auxiliary:
        repository: docker.io/ibmcom/db2u.auxiliary.auth
        tag: 11.5.1.0-CN1
      db2_init:
        repository: docker.io/ibmcom/db2u.instdb
        tag: 11.5.1.0-CN1
      db2_etcd:
        repository: quay.io/coreos/etcd
        tag: v3.3.10
      db2_alpine: 
        repository: docker.io/alpine
        tag: 3.6
      openldap:
        repository: osixia/openldap
        tag: 1.3.0
      busybox:
        repository: docker.io/library/busybox
        tag: latest
      phpldapadmin:
        repository: osixia/phpldapadmin
        tag: 0.9.0
  ########################################################################
  ########   IBM Business Automation Navigator configuration      ########
  ########################################################################
  navigator_configuration:
    image:
      repository: cp.icr.io/cp/cp4a/ban/navigator-sso
      tag: ga-308-icn-la002
  ########################################################################
  ########      IBM Business Automation Studio configuration      ########
  ########################################################################
  bastudio_configuration:
    images:
      bastudio:
        repository: cp.icr.io/cp/cp4a/bas/bastudio
        tag: 20.0.2-IF002
    jms_server:
      image:
        repository: cp.icr.io/cp/cp4a/bas/jms
        tag: 20.0.2-IF002
    playback_server:
      images:
        db_job:
          repository: cp.icr.io/cp/cp4a/bas/solution-server-helmjob-db
          tag: 20.0.2-IF002
        solution_server:
          repository: cp.icr.io/cp/cp4a/bas/solution-server
          tag: 20.0.2-IF002
  ########################################################################
  ########      IBM Resource Registry configuration               ########
  ########################################################################
  resource_registry_configuration:
    images:
      resource_registry:
        repository: cp.icr.io/cp/cp4a/aae/dba-etcd
        tag: 20.0.2-IF002
        
  ########################################################################
  ########   IBM User and Group Management Service configuration  ########
  ########################################################################
  ums_configuration:
    teamserver:
      admingroup: P8Administrators
      