apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-iam-config-job
  namespace: "zenNamespace"
  labels:
    component: cpfs
spec:
  podSelector:
    matchLabels:
      component: "iam-config-job"
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}